name: Unit Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7.x, 3.8.x, 3.9.x, 3.10.x, 3.11.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Dependencies
        run: python -m pip install -r requirements-test.txt

      - name: Run Unit Test
        run: python -m unittest smartpay/test/specs/unit.py
